dist: bionic

language: python

python:
  - '3.8'

os: 
  - linux
before_install:
  - sudo apt-get -y install doxygen

install:
  - pip install -U codespell
  - pip install -U travis-sphinx
  - pip install -U sphinx-rtd-theme
  - pip install -U breathe
  - pip install -U exhale

before_script:
 - wget "https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2019q4/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2"
 - tar xvf gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2
 - export PATH=$PWD/gcc-arm-none-eabi-9-2019-q4-major/bin/:$PATH




jobs:
  include:
    # Code spell
    - name: "Code-spell" 
      script: ./dist/tools/codespell/check.sh
    # Build test
    - name: "Build-Test"
      script: make

